/*
============================================================
E-COMMERCE USER ENGAGEMENT ANALYSIS
File: 07_user_engagement.sql
Dataset: RetailRocket E-commerce Dataset
============================================================

PURPOSE:
Analyze visitor engagement and determine how browsing
behavior is associated with purchase conversion.

BUSINESS QUESTIONS:

1. How active are individual visitors?
2. How many products does each visitor view?
3. Which visitors eventually make a purchase?
4. Does higher engagement correspond to higher conversion?
5. How does conversion change as the number of product
   views increases?
6. Which engagement group has the highest conversion?

ENGAGEMENT DEFINITION:

Low:
    1-2 product views

Medium:
    3-5 product views

High:
    More than 5 product views

IMPORTANT:
These results show association, not causation.

A higher number of product views is associated with higher
conversion, but this does not prove that viewing more
products causes a visitor to purchase.

DATA LIMITATION:
The dataset contains anonymous behavioral events and may
not capture every interaction in a customer's journey.
*/

-- ============================================================
-- 1. VISITOR-LEVEL BEHAVIOR SUMMARY
-- ============================================================

WITH visitor_summary AS (

    SELECT
        visitorid,

        -- Total number of events generated by the visitor
        COUNT(*) AS total_events,

        -- Number of product view events
        COUNT(*) FILTER (
            WHERE event = 'view'
        ) AS total_views,

        -- Number of cart events
        COUNT(*) FILTER (
            WHERE event = 'addtocart'
        ) AS total_cart_events,

        -- Number of purchase events
        COUNT(*) FILTER (
            WHERE event = 'transaction'
        ) AS total_purchases,

        -- Number of different products viewed
        COUNT(DISTINCT itemid) FILTER (
            WHERE event = 'view'
        ) AS unique_products_viewed

    FROM events

    GROUP BY visitorid
)

SELECT *
FROM visitor_summary
LIMIT 10;

-- ============================================================
-- 2. IDENTIFY PURCHASERS
-- ============================================================

WITH visitor_summary AS (

    SELECT
        visitorid,

        COUNT(*) AS total_events,

        COUNT(*) FILTER (
            WHERE event = 'view'
        ) AS total_views,

        COUNT(*) FILTER (
            WHERE event = 'addtocart'
        ) AS total_cart_events,

        COUNT(*) FILTER (
            WHERE event = 'transaction'
        ) AS total_purchases,

        COUNT(DISTINCT itemid) FILTER (
            WHERE event = 'view'
        ) AS unique_products_viewed

    FROM events

    GROUP BY visitorid
),

visitor_behavior AS (

    SELECT
        *,
        
        CASE
            WHEN total_purchases > 0
            THEN 1
            ELSE 0
        END AS purchased

    FROM visitor_summary
)

SELECT *
FROM visitor_behavior
LIMIT 10;

-- ============================================================
-- 3. CREATE ENGAGEMENT SEGMENTS
-- ============================================================

WITH visitor_summary AS (

    SELECT
        visitorid,

        COUNT(*) AS total_events,

        COUNT(*) FILTER (
            WHERE event = 'view'
        ) AS total_views,

        COUNT(*) FILTER (
            WHERE event = 'addtocart'
        ) AS total_cart_events,

        COUNT(*) FILTER (
            WHERE event = 'transaction'
        ) AS total_purchases,

        COUNT(DISTINCT itemid) FILTER (
            WHERE event = 'view'
        ) AS unique_products_viewed

    FROM events

    GROUP BY visitorid
),

visitor_behavior AS (

    SELECT
        *,
        
        CASE
            WHEN total_purchases > 0
            THEN 1
            ELSE 0
        END AS purchased

    FROM visitor_summary
),

engagement_segments AS (

    SELECT
        *,

        CASE
            WHEN total_views <= 2
                THEN 'Low'

            WHEN total_views <= 5
                THEN 'Medium'

            ELSE 'High'
        END AS engagement

    FROM visitor_behavior
)

SELECT *
FROM engagement_segments
LIMIT 20;